USE AppRevistas;
SELECT * FROM Usuario WHERE nombre_usuario = 'admin';
SELECT * FROM TipoUsuario;
SELECT * FROM Usuario;
SELECT * FROM Perfil;
DESCRIBE Perfil;
SELECT * FROM Perfil_Etiquetas;
SELECT * FROM Anunciante;
SELECT * FROM Etiqueta;
SELECT * FROM Revista_Etiquetas;
DESCRIBE Revista;
INSERT INTO Revista (revista, titulo, descripcion, no_version, precio_costo,aprobado,suscripciones, precio_suscripcion, es_pago, tiene_comentarios, tiene_reacciones,fecha, R_nombre_usuario) VALUES("pathRevista", "Titulo", "debe tener descripcion", 1,1, 0,1, 0, 0, true,true,"2021-10-13","editor");
SELECT idRevista, RE_nombre_etiqueta FROM Revista INNER JOIN Revista_Etiquetas ON Revista.idRevista = Revista_Etiquetas.RE_idRevista;
SELECT * FROM Revista WHERE R_nombre_usuario = "editor";
SELECT * FROM Revista ORDER BY idRevista DESC;
SELECT * FROM Usuario;
SELECT * FROM Revista_Etiquetas WHERE RE_idRevista = 2;
SELECT * FROM Reaccion_Revista WHERE RR_idRevista = 1 AND RR_nombre_usuario = "lector";
SELECT * FROM Reaccion;
SELECT * FROM Reaccion_Revista;
SELECT * FROM Comentario ORDER BY fecha;
DESCRIBE Comentario;
SELECT * FROM Revista WHERE EXISTS (SELECT S_idRevista FROM Suscripcion WHERE S_usuario_lector = "lector" AND fecha_final >= NOW());
SELECT * FROM Suscripcion WHERE fecha_final >= NOW() AND S_idRevista= 1;
SELECT * FROM Pago;
DESCRIBE CambioRevista;
ALTER TABLE CambioRevista MODIFY COLUMN idCambioRevista int AUTO_INCREMENT;
INSERT INTO CambioRevista(precio_costo, fecha_inicio, CR_idRevista, CR_nombre_usuario) VALUES (2,"2021-03-10",1,"editor");
UPDATE CambioRevista SET fecha_final = "2021-04-10" WHERE idCambioRevista = (SELECT idCambioRevista FROM CambioRevista WHERE CR_idRevista = 1 ORDER BY idCambioRevista DESC LIMIT 1);
SELECT * FROM ValoresSistema;
SELECT * FROM Suscripcion;
SELECT * FROM Revista WHERE idRevista = EXISTS (SELECT S_idRevista FROM Suscripcion WHERE S_usuario_lector = "lector" AND fecha_final >= NOW());
SELECT * FROM Revista WHERE fecha BETWEEN "" AND "";
SELECT * FROM Anuncio;
SELECT * FROM Anuncio_Etiquetas;
INSERT INTO Anunciante VALUES("PEPE",51806388);
INSERT INTO Anuncio(tipo_anuncio,texto,video_url,imagen_path,activo,fecha_inicio,fecha_final,pago,A_nombre_anunciante) VALUES(1,"TEXTO","VIDEO","IMAGEN",0,"2021-10-25","2021-10-26",800,"PEPE");
UPDATE Anuncio SET activo = 1 WHERE idAnuncio = 2;
SELECT AE_idAnuncio FROM Anuncio_Etiquetas WHERE AE_nombre_etiqueta IN('CUNOC', 'Ingeniería', 'Real Madrid') GROUP BY AE_idAnuncio;
SELECT RE_idRevista FROM Revista_Etiquetas WHERE RE_nombre_etiqueta IN ('CUNOC') GROUP BY RE_idRevista;
SELECT * FROM Revista WHERE aprobado = 0 AND idRevista IN (SELECT RE_idRevista FROM Revista_Etiquetas WHERE RE_nombre_etiqueta IN ('CUNOC') GROUP BY RE_idRevista);
SELECT * FROM Anuncio WHERE EXISTS (SELECT * FROM Anuncio_Etiquetas WHERE AE_nombre_etiqueta = 'CUNOC');
SELECT * FROM Etiqueta;
SELECT idRevista FROM Revista WHERE aprobado = 1 AND idRevista IN (SELECT RE_idRevista FROM Revista_Etiquetas WHERE RE_nombre_etiqueta IN ('Comida','Computadoras','Audifonos','Ingeniería','Cocina','Base de Datos','Mouse','Silla','Monitor','Perro','PepePollo','Mesa','CUNOC') GROUP BY RE_idRevista);
SELECT * FROM Anuncio;
UPDATE Revista SET tiene_comentarios = 0, tiene_reacciones = 0, suscripciones = 0 WHERE idRevista = ?;
SELECT * FROM Comentario_Revista;
SELECT * FROM Comentario WHERE idComentario IN (SELECT CR_idComentario FROM Comentario_Revista WHERE fecha BETWEEN "2013-08-01" AND "2021-11-11");
SELECT * FROM Revista WHERE idRevista = 1 AND R_nombre_usuario = "editor" AND fecha BETWEEN "2021-01-01" AND "2021-12-12";
SELECT * FROM Comentario_Revista;
SELECT * FROM Comentario WHERE idComentario IN (SELECT * FROM Comentario_Revista WHERE CR_idRevista = 2 AND fecha BETWEEN "2013-08-01" AND "2021-11-11");
SELECT * FROM Comentario_Revista WHERE CR_idRevista = 1 ORDER BY fecha;
SELECT * FROM Suscripcion WHERE S_idRevista = 1;
SELECT * FROM Reaccion_Revista WHERE RR_idRevista = 1 AND fecha BETWEEN ? AND ?;
SELECT * FROM Suscripcion WHERE S_idRevista = 1;
SELECT * FROM Reaccion_Revista;
SELECT RR_idRevista,COUNT(RR_idRevista) as total  FROM Reaccion_Revista WHERE fecha BETWEEN "2021-01-01" AND "202-02-01" group by RR_idRevista ORDER BY total desc;
SELECT * FROM Revista WHERE idRevista IN (SELECT RR_idRevista,COUNT(RR_idRevista) as total  FROM Reaccion_Revista WHERE fecha BETWEEN "2021-01-01" AND "202-02-01" group by RR_idRevista ORDER BY total desc);
SELECT *  FROM Reaccion_Revista WHERE RR_idREvista = 1;
SELECT * FROM Reaccion_Revista WHERE RR_idRevista = 1 AND fecha BETWEEN "2020-01-01" AND "2022-01-01";
SELECT * FROM Comentario_Revista;
SELECT S_idRevista,COUNT(S_idRevista) As veces FROM Suscripcion WHERE fecha_inicio BETWEEN ? AND ? GROUP BY S_idRevista ORDER BY veces DESC LIMIT 5;
SELECT CR_idRevista, COUNT(CR_idRevista) As veces FROM Comentario_Revista WHERE fecha BETWEEN ? AND ? GROUP BY CR_idRevista ORDER BY veces DESC LIMIT 5;
SELECT * FROM Suscripcion;
SELECT * FROM Anunciante;
SELECT * FROM Anuncio WHERE fecha_inicio BETWEEN "2021-10-24" AND "2021-10-25" AND A_nombre_anunciante = "Chemsitos Inc";
SELECT * FROM Anuncio GROUP BY A_nombre_anunciante;
SELECT * FROM Anuncio WHERE fecha_inicio BETWEEN "2021-01-01" AND "2021-01-01" AND A_nombre_anunciante = "cheemsitos inc";
SELECT * FROM Anuncio WHERE activo = 1 AND idAnuncio IN (SELECT AE_idAnuncio FROM Anuncio_Etiquetas WHERE AE_nombre_etiqueta IN ('Comida','Computadoras','Audifonos','Ingeniería','Cocina','Base de Datos','Mouse','Silla','Monitor','Perro','PepePollo','Mesa','CUNOC') GROUP BY AE_idAnuncio);
SELECT * FROM Anuncio_Etiquetas;SELECT * FROM Anuncio;